### ISSUE TITLE
Markdown files do not get formatted

### ISSUE THREAD

**Issue by rgeorgiev583** [sumnow/markdown-formatter#14] opened 2019-11-24 20:18 UTC
## Steps to reproduce

Invoke the **Format Document** command on a Markdown file.

## Expected behavior

The file should get formatted.

## Actual behavior

The file does not get formatted; instead, VSCode displays a notification that **There is no formatter for 'markdown' files installed.**, even though I already have the _markdown-formatter_ extension installed.

Version 0.7.5 of the extension used to work properly but as of 0.7.6, the aforementioned notification appears for every Markdown file which I try to format.

**Comment by nathanbegbie** [comment] 2019-11-27 10:25
I am also experiencing this issue with `0.7.6`. 

You can install  version `0.7.5` by right clicking on the package listed in the extensions bar and selecting `Install Another Version . . .` I was able to successfully install the extension and format my document as expected.

**Comment by sumnow** [comment] 2019-12-09 10:22
I'm sorry about this issue.
The problem is that the 0.7.6 version is incomplete and has been fixed in the 0.7.7 version. Thank you.

**Comment by sumnow** [comment] 2019-12-09 10:23
I'm sorry about this issue.
The problem is that the 0.7.6 version is incomplete and has been fixed in the 0.7.8 version. Thank you

**Closed by sumnow** 2019-12-09 10:23 UTC

**Comment by nathanbegbie** [comment] 2019-12-09 10:25
Thanks for addressing this @sumnow! Your package is appreciated :D
